# Generated by Django 3.1.3 on 2021-05-10 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Enrollapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='school_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Enrollapp.schools'),
            preserve_default=False,
        ),
    ]
