# Generated by Django 3.1.3 on 2021-03-24 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Enrollapp', '0002_schools'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='standard',
            field=models.CharField(choices=[('8', 'Class 8'), ('9', 'Class 9'), ('10', 'Class 10'), ('11', 'Class 11'), ('12', 'Class 12')], default=8, max_length=4),
            preserve_default=False,
        ),
    ]
