# Generated by Django 3.1.3 on 2021-05-10 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Enrollapp', '0002_userprofileinfo_school_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='school_name',
        ),
    ]
