# Generated by Django 3.1.3 on 2021-04-13 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Enrollapp', '0003_userprofileinfo_standard'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='sis_id',
            field=models.IntegerField(default=1),
        ),
    ]
