# Generated by Django 3.1.3 on 2021-04-17 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Enrollapp', '0005_auto_20210417_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='Role',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='date_of_birth',
            field=models.DateField(max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='standard',
            field=models.CharField(max_length=4),
        ),
    ]
