# Generated by Django 3.1.3 on 2021-04-14 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Enrollapp', '0005_auto_20210414_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='Role',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='standard',
            field=models.CharField(max_length=4),
        ),
    ]
