# Generated by Django 3.1.3 on 2021-04-14 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Enrollapp', '0006_auto_20210414_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='school_namme',
            field=models.CharField(default='NagaEd Digital School', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='gender',
            field=models.CharField(max_length=1),
        ),
    ]
