# Generated by Django 3.1.3 on 2021-04-19 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Enrollapp', '0006_auto_20210417_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='date_of_birth',
            field=models.CharField(max_length=20),
        ),
    ]
