# Generated by Django 3.1.3 on 2021-04-20 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Enrollapp', '0008_auto_20210419_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='gender',
            field=models.CharField(max_length=10),
        ),
    ]
